import { validateAst } from './schema.js';
import { canonical, sha256 } from './document.js';
import { evaluatePolicy } from './evaluate.js';

export function compilePolicy(envelope, config, document, { demo = false } = {}) {
  validateAst(envelope.ast, document.text);
  if (envelope.source.sha256 !== document.sha256 || envelope.source.textSha256 !== document.textSha256) throw new Error('Source document hash mismatch');
  if (envelope.ast.unresolved.length && !demo) throw new Error('Unresolved legal terms cannot be compiled for execution. Use --demo only for local simulation.');
  if (envelope.ast.rules.some((r) => r.action === 'transfer' && r.effect === 'permit')) throw new Error('Transfer permissions are unsupported by the custodial MVP');
  if (config.decimals !== 6 || config.custody !== 'backend' || config.currency !== 'USD' || config.priceModel !== 'one-token-per-usd') throw new Error('Only the six-decimal custodial USD demo price model is implemented');
  if (!/^[1-9][0-9]{0,77}$/.test(config.maxSupply) || BigInt(config.maxSupply) >= 2n ** 256n) throw new Error('Invalid uint256 supply cap');
  for (const value of [config.name, config.symbol]) if (typeof value !== 'string' || !/^[A-Za-z0-9 ._-]{1,64}$/.test(value)) throw new Error('Invalid token name or symbol');
  if (!Array.isArray(config.assumptions) || config.assumptions.length === 0) throw new Error('Explicit deployment assumptions are required');
  const policy = { version: 1, demo, source: envelope.source, ast: envelope.ast, config };
  policy.hash = `0x${sha256(canonical(policy))}`;
  const enabled = (action) => envelope.ast.rules.some((rule) => rule.action === action && rule.effect === 'permit');
  const solidity = `// SPDX-License-Identifier: MIT
// Generated by Mirrortech. Legal facts are attested and enforced by the backend.
pragma solidity ^0.8.24;
import {MirrorToken} from "./MirrorToken.sol";
contract CompiledMirrorToken is MirrorToken {
    constructor(address admin, address minter) MirrorToken(
        ${JSON.stringify(config.name)}, ${JSON.stringify(config.symbol)}, admin, minter,
        ${policy.hash}, ${config.maxSupply}, ${enabled('mint')}, ${enabled('burn')}
    ) {}
}
`;
  const javascript = `// Generated from validated data; no model-generated code is executed.\nexport const policy = ${JSON.stringify(policy, null, 2)};\n${evaluatePolicy.toString()}\nexport const evaluate = (action, facts) => evaluatePolicy(policy.ast, action, facts);\n`;
  return { policy, solidity, javascript };
}

export function verifyPolicy(policy) {
  const { hash, ...content } = policy;
  if (hash !== `0x${sha256(canonical(content))}`) throw new Error('Compiled policy integrity check failed');
  validateAst(policy.ast);
  return policy;
}
