// Emits the on-chain half of a compiled policy: one encoded program per action, plus the hash of
// the clause table that decodes a revert back into the sentence a lawyer wrote.
import { AbiCoder } from 'ethers';
import { ACTIONS, FACTS } from '../policy/schema.js';
import { buildProgram } from '../policy/dnf.js';
import { canonical, sha256 } from '../policy/document.js';

const EFFECTS = { permit: 0, require: 1, forbid: 2 };
const RULE_TUPLE = 'tuple(uint8 effect,uint16 clauseId,uint256[] pos,uint256[] neg)[]';

export function encodeProgram(rules) {
  return AbiCoder.defaultAbiCoder().encode([RULE_TUPLE], [rules.map((rule) => [
    EFFECTS[rule.effect], rule.clauseId, rule.terms.map((term) => term.pos), rule.terms.map((term) => term.neg),
  ])]);
}

export function buildOnchainPolicy(ast) {
  const program = buildProgram(ast);
  const programs = program.byAction.map(encodeProgram);
  const clauseTableHash = `0x${sha256(canonical(program.clauses))}`;
  return { ...program, programs, clauseTableHash };
}

export function emitCompiledPolicy(onchain, policyHash) {
  const branches = onchain.programs
    .map((bytes, index) => `        if (action == ${index}) return hex"${bytes.slice(2)}"; // ${ACTIONS[index]}`)
    .join('\n');
  const factList = FACTS.map((name, index) => `    uint256 internal constant FACT_${name.replace(/([A-Z])/g, '_$1').toUpperCase()} = 1 << ${index};`).join('\n');
  const actionList = ACTIONS.map((name, index) => `    uint8 internal constant ACTION_${name.replace(/([A-Z])/g, '_$1').toUpperCase()} = ${index};`).join('\n');
  return `// SPDX-License-Identifier: UNLICENSED
// Generated by Mirrortech from a hashed source document. Do not edit.
pragma solidity ^0.8.24;

/// @notice The compiled policy, byte for byte, as the off-chain interpreter evaluates it.
/// @dev Every program below is proved equivalent to the JavaScript interpreter over all
/// three-valued fact assignments before it is emitted.
library CompiledPolicy {
    /// @notice Binds this policy to one source document and one set of deployment assumptions.
    bytes32 internal constant POLICY_HASH = ${policyHash};

    /// @notice Hash of the clause table that maps a revert's clauseId to its verbatim quote.
    /// A front end that decodes a denial cannot be pointed at a substituted quote.
    bytes32 internal constant CLAUSE_TABLE_HASH = ${onchain.clauseTableHash};

    uint256 internal constant FACT_COUNT = ${FACTS.length};
    uint256 internal constant ACTION_COUNT = ${ACTIONS.length};

${actionList}

${factList}

    error UnknownAction(uint8 action);

    /// @notice The rule program for one action, ready for PolicyEval.decide.
    function program(uint8 action) internal pure returns (bytes memory) {
${branches}
        revert UnknownAction(action);
    }
}
`;
}

export const ACTION_INDEX = Object.fromEntries(ACTIONS.map((action, index) => [action, index]));
export const FACT_BIT = Object.fromEntries(FACTS.map((fact, index) => [fact, 1n << BigInt(index)]));

// Emit only fixed token templates from validated policy data.
export function emitToken(policy) {
  const { ast, profile, config, cashier } = policy;
  const enabled = (action) => ast.rules.some((rule) => rule.action === action && rule.effect === 'permit');
  return profile !== 'wildcat-credit' ? `// SPDX-License-Identifier: UNLICENSED
// Generated by Mirrortech. Legal facts are attested and enforced by the backend.
pragma solidity ^0.8.24;
import {${cashier ? 'MirrorCashierToken' : 'MirrorToken'}} from "../contracts/${cashier ? 'MirrorCashierToken' : 'MirrorToken'}.sol";
contract CompiledMirrorToken is ${cashier ? 'MirrorCashierToken' : 'MirrorToken'} {
    constructor(address admin, address minter) ${cashier ? 'MirrorCashierToken' : 'MirrorToken'}(
        ${JSON.stringify(config.name)}, ${JSON.stringify(config.symbol)}, admin, minter,
        ${policy.hash}, ${config.maxSupply}, ${enabled('mint')}, ${enabled('burn')}
    ) {}
}
` : null;
}
