"use client";

import { useState } from "react";
import { plainSummary } from "@/lib/labels";
import { confidenceLabel } from "@/lib/verification";
import type { PolicyData, Verification as VerificationReport } from "@/lib/types";
import { Disclosure, Glyph } from "../_components/common";

const STATE = {
  verified: "true",
  contested: "unknown",
  unverified: "unknown",
  wrong: "false",
  unknown: "unknown",
} as const;

/** One claim as the API returns it, and the confidence entry it produces: the shape, shown on real data. */
function Schema({ v }: { v: VerificationReport }) {
  const sample = v.claims.find((c) => c.verdicts.some((x) => x.verdict === "contested")) ?? v.claims[0];
  const shape = {
    claim: sample && {
      key: sample.key,
      claim_id: "6-char hex",
      claim: sample.claim,
      verdicts: sample.verdicts.map((x) => ({
        evaluator_agent_id: x.agent,
        verdict: x.verdict,
        reason: x.reason,
      })),
      disputed: sample.disputed,
    },
    contested: v.contested[0] ?? null,
    confidence: {
      overall: v.confidence.overall,
      counts: v.confidence.counts,
      byRef: Object.fromEntries(Object.entries(v.confidence.byRef).slice(0, 2)),
    },
  };
  return <pre className="schema">{JSON.stringify(shape, null, 2)}</pre>;
}

/** What Noolog established about the extraction: verdict counts, every claim, what was contested, the confidence. */
export function Verification({ policy, onSelect }: { policy: PolicyData; onSelect: (ref: string) => void }) {
  const v = policy.verification;
  const [filter, setFilter] = useState<"all" | "contested">("all");
  if (!v) return null;
  const { counts } = v.confidence;
  const shown =
    filter === "all" ? v.claims : v.claims.filter((c) => c.verdicts.some((x) => x.verdict !== "verified"));
  const jump = (ref: string | null) => {
    if (ref && (ref.startsWith("rule:") || ref.startsWith("term:"))) onSelect(ref);
  };
  return (
    <section className="card verification" aria-label="Verification by Noolog">
      <div className="row" style={{ alignItems: "baseline", gap: 12, flexWrap: "wrap" }}>
        <h2 style={{ margin: 0 }}>Generated by Noolog</h2>
        <span className="meta">
          confidence <strong>{v.confidence.overall.toFixed(2)}</strong> (
          {confidenceLabel(v.confidence.overall)}) · winner {v.winner?.agent} after {v.rounds} rounds ·
          convergence {v.convergence?.toFixed(2)}
        </span>
      </div>
      <p className="actions-line">
        <span>
          <Glyph state="true" /> {counts.verified} verified
        </span>
        <span>
          <Glyph state="unknown" /> {counts.contested} contested
        </span>
        <span>
          <Glyph state="unknown" /> {counts.unverified} unverified
        </span>
        <span>
          <Glyph state="false" /> {counts.wrong} wrong
        </span>
      </p>
      {v.contested.length > 0 && (
        <Disclosure title="Contested items" summary={`${v.contested.length} the critic pushed back on`} open>
          <ul className="plain-list">
            {v.contested.map((item, i) => (
              <li key={`${item.key}-${i}`}>
                <button className="linkish" onClick={() => jump(item.ref)}>
                  {plainSummary(item.claim)}
                </button>
                <div className="meta">
                  {item.evaluator}: {item.position} · confidence {item.confidence}
                  {item.verdict ? ` · verdict ${item.verdict}` : ""}
                </div>
              </li>
            ))}
          </ul>
        </Disclosure>
      )}
      <Disclosure
        title="Every claim"
        summary={`${v.confidence.total} claims · ${v.confidence.verified} verified`}
      >
        <div className="cov-filters" role="radiogroup" aria-label="Claims shown" style={{ marginBottom: 6 }}>
          {(["all", "contested"] as const).map((value) => (
            <button
              key={value}
              type="button"
              role="radio"
              aria-checked={filter === value}
              className={`cov-filter ${filter === value ? "on" : ""}`}
              onClick={() => setFilter(value)}
            >
              {value === "all" ? "All" : "Not verified"}
            </button>
          ))}
        </div>
        <div className="tbl-wrap">
          <table className="tbl">
            <thead>
              <tr>
                <th>Claim</th>
                <th>About</th>
                <th>Verdicts</th>
                <th>Confidence</th>
              </tr>
            </thead>
            <tbody>
              {shown.map((claim) => (
                <tr key={claim.key} className="clickable" onClick={() => jump(claim.ref)}>
                  <td className="small">{plainSummary(claim.claim)}</td>
                  <td className="small">{claim.ref}</td>
                  <td className="small">
                    {claim.verdicts.map((x) => (
                      <span key={x.agent} title={x.reason ?? undefined}>
                        <Glyph state={STATE[x.verdict]} /> {x.verdict} · {x.agent}{" "}
                      </span>
                    ))}
                  </td>
                  <td className="small">{(v.confidence.byRef[claim.ref] ?? claim.score).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Disclosure>
      <Disclosure
        title="Schema"
        summary="a claim, a contested item and the confidence entry, as the API returns them"
      >
        <Schema v={v} />
      </Disclosure>
    </section>
  );
}
